name: CI with Conda & CodeCarbon CLI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout your code
      - uses: actions/checkout@v4

      # 2️⃣ Install Miniforge (Conda) without auto-activation
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          mamba-version: ""       # disable mamba entirely
          miniforge-version: "latest"

      # 3️⃣ Create your conda env explicitly (named 'lunar-env')
      - name: Create Conda environment
        run: |
          conda env create -f environment.yml -n lunar-env

      # 4️⃣ Install CodeCarbon CLI into that environment
      - name: Install CodeCarbon
        run: |
          conda run -n lunar-env pip install --upgrade codecarbon

      # 5️⃣ (Optional) Check that Python is correct
      - name: Check Python version
        run: |
          conda run -n lunar-env python --version

      # 6️⃣ Run your script under CodeCarbon via the CLI
      - name: Track emissions for main.py
        run: |
          conda run -n lunar-env codecarbon run \
            --project-name LunarLanderCLI \
            --json-output emissions.json \
            python main.py

      # 7️⃣ Upload the emissions.json artifact
      - name: Upload emissions.json
        uses: actions/upload-artifact@v4
        with:
          name: emissions
          path: emissions.json
