name: CI with Conda & CodeCarbon CLI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout your code
      - uses: actions/checkout@v4

      # 2️⃣ Install Miniforge & create+activate your env from environment.yml
      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          miniforge-version: "latest"
          # Tell it to build & activate your env in one go:
          environment-file: environment.yml
          environment-name: lunar-env
          activate-environment: lunar-env

      # 3️⃣ Verify Python version in the activated env
      - name: Check Python
        run: python --version

      # 4️⃣ Install CodeCarbon CLI in that same env
      - name: Install CodeCarbon
        run: pip install --upgrade codecarbon

      # 5️⃣ Run your script through CodeCarbon CLI
      - name: Run main.py with CodeCarbon
        run: |
          codecarbon run \
            --project-name LunarLanderCLI \
            --json-output emissions.json \
            python main.py

      # 6️⃣ Upload the emissions.json artifact
      - name: Upload emissions.json
        uses: actions/upload-artifact@v4
        with:
          name: emissions
          path: emissions.json
