name: Run CodeCarbon Emissions Tracker

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  track-emissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install CodeCarbon
      shell: bash -l {0}
      run: |
        pip install codecarbon

    - name: Create wrapper to run main.py with CodeCarbon
      shell: bash -l {0}
      run: |
        echo "from codecarbon import EmissionsTracker" > run_with_emissions.py
        echo "tracker = EmissionsTracker()" >> run_with_emissions.py
        echo "tracker.start()" >> run_with_emissions.py
        echo "exec(open('main.py').read())" >> run_with_emissions.py
        echo "tracker.stop()" >> run_with_emissions.py

    - name: Run main.py with CodeCarbon tracker
      shell: bash -l {0}
      run: |
        python run_with_emissions.py

    - name: Upload emissions output
      uses: actions/upload-artifact@v4
      with:
        name: codecarbon-emissions
        path: emissions.csv
