name: Update Emissions Trend

on:
  workflow_run:
    workflows: ["Run CodeCarbon Emissions Tracker"]
    types: 
      - completed

permissions:
  contents: write

jobs:
  # UPDATE GRAPH
  update-trend-graph:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # whole history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install plotting deps
        run: pip install pandas matplotlib

      - name: Fetch last emissions artifact (first-time safe)
        uses: actions/download-artifact@v4
        with:
          name: codecarbon-emissions
          path: .
