name: Update Emissions Trend

# Only run on a push to main (i.e. after a PR merge)
on:
  push:
    branches: [ main ]

permissions:
  contents: write    # needed to commit back to the repo

jobs:
  update-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # need full history to append/commit
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas matplotlib

      - name: Download last emissions artifact
        uses: actions/download-artifact@v3
        with:
          name: codecarbon-emissions
          path: .

      - name: Append to history CSV
        run: |
          # Ensure we have a history file; initialize if missing
          if [ ! -f emissions_history.csv ]; then
            echo "date,emissions_kg,energy_kwh" > emissions_history.csv
          fi
          # Extract the latest row from emissions.csv
          python - << 'EOF'
          import pandas as pd
          from datetime import datetime

          # Read the latest run
          df = pd.read_csv("emissions.csv")
          latest = df.iloc[-1]
          # Build a one‐line dataframe
          row = pd.DataFrame({
              "date": [datetime.utcnow().strftime("%Y-%m-%d")],
              "emissions_kg": [latest.emissions_in_kg if hasattr(latest, "emissions_in_kg") else latest.emissions],
              "energy_kwh": [latest.energy_consumed]
          })
          row.to_csv("emissions_history.csv", mode="a", header=False, index=False)
          EOF

      - name: Generate trend plot
        run: |
          python - << 'EOF'
          import pandas as pd
          import matplotlib.pyplot as plt

          # Load history
          hist = pd.read_csv("emissions_history.csv", parse_dates=["date"])
          plt.plot(hist.date, hist.emissions_kg)
          plt.xlabel("Date")
          plt.ylabel("CO₂ emissions (kg)")
          plt.tight_layout()
          plt.savefig("emissions_trend.png")
          EOF

                - name: Update README with new graph
                  run: |
                    # If README.md already embeds the file, this is a no‑op.
                    # Otherwise ensure there's a placeholder like <!-- EMISSIONS_GRAPH --> in your README.
                    sed -i '/<!-- EMISSIONS_GRAPH -->/,/<!-- END_EMISSIONS_GRAPH -->/c\
          <!-- EMISSIONS_GRAPH -->\
          ![Emissions Trend](emissions_trend.png)\
          <!-- END_EMISSIONS_GRAPH -->' README.md

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add emissions_history.csv emissions_trend.png README.md
          git commit -m "chore: update emissions trend graph [ci skip]" || echo "No changes to commit"
          git push
